export const stocks = [
    {
      id: 1,
      category: "Piston Valves",
      valveSize: "0.5''",
      rating: " 800#",
      endconnection: "SW",
      moc: "A105",
      qty: 50,
      Indvalvedim: "80x90x109",
      indvalveweights: "1.2",
    },
    {
      id: 2,
      category: "Piston Valves",
      valveSize: "0.5''",
      rating: "150#",
      endconnection: "RF",
      moc: "A105",
      qty: 10,
      Indvalvedim: "85x90x109",
      indvalveweights: "1.2",
    },
    {
      id: 3,
      category: "Piston Valves",
      valveSize: "3/4''",
      rating: "800#",
      endconnection: "SW",
      moc: "A105",
      qty: 50,
      Indvalvedim: "100x110x140",
      indvalveweights: "1.8",
    },
    {
      id: 4,
      category: "Piston Valves",
      valveSize: "3/4''",
      rating: "150#",
      endconnection: "RF",
      moc: "A105",
      qty: 10,
      Indvalvedim: "100x110x140",
      indvalveweights: "1.8",
    },
    {
      id: 5,
      category: "Piston Valves",
      valveSize: "1''",
      rating: "800#",
      endconnection: "SW",
      moc: "A105",
      qty: 50,
      Indvalvedim: "120x135x170",
      indvalveweights: "3.2",
    },
    {
      id: 6,
      category: "Piston Valves",
      valveSize: "1''",
      rating: "150#",
      endconnection: "RF",
      moc: "A105",
      qty: 10,
      Indvalvedim: "120x135x170",
      indvalveweights: "3.2",
    },
    {
      id: 7,
      category: "Piston Valves",
      valveSize: "1.5''",
      rating: "800#",
      endconnection: "SW",
      moc: "A105",
      qty: 15,
      Indvalvedim: "160x170x215",
      indvalveweights: "6.8",
    },
    {
      id: 8,
      category: "Piston Valves",
      valveSize: "1.5''",
      rating: "150#",
      endconnection: "RF",
      moc: "A105",
      qty: 10,
      Indvalvedim: "160x170x215",
      indvalveweights: "6.8",
    },
    {
      id: 9,
      category: "Piston Valves",
      valveSize: "2''",
      rating: "150#",
      endconnection: "RF",
      moc: "A216 WCB",
      qty: 10,
      Indvalvedim: "185x195x250",
      indvalveweights: "10.2",
    },
    {
      id: 10,
      category: "Piston Valves",
      valveSize: "2.5''",
      rating: "150#",
      endconnection: "RF",
      moc: "A216 WCB",
      qty: 5,
      Indvalvedim: "241x375x435",
      indvalveweights: "40",
    },
    {
      id: 11,
      category: "Piston Valves",
      valveSize: "3''",
      rating: "150#",
      endconnection: "RF",
      moc: "A216 WCB",
      qty: 5,
      Indvalvedim: "241x375x435",
      indvalveweights: "40",
    },
    {
      id: 12,
      category: "Piston Valves",
      valveSize: "4''",
      rating: "150#",
      endconnection: "RF",
      moc: "A216 WCB",
      qty: 5,
      Indvalvedim: "292x415x490",
      indvalveweights: "50",
    },
    {
      id: 13,
      category: "Piston Valves",
      valveSize: "6''",
      rating: "150#",
      endconnection: "RF",
      moc: "A216 WCB",
      qty: 2,
      Indvalvedim: "406x495x590",
      indvalveweights: "98",
    },
    {
      id: 14,
      category: "Piston Valves",
      valveSize: "8''",
      rating: "150#",
      endconnection: "RF",
      moc: "A216 WCB",
      qty: 2,
      Indvalvedim: "406x495x590",
      indvalveweights: "98",
    },
    {
        id: 145,
        category: " ",
        valveSize: " ",
        rating: " ",
        endconnection: " ",
        moc: " ",
        qty: " ",
        Indvalvedim: " ",
        indvalveweights: " ",
      },
    {
      id: 15,
      category: "Gate",
      valveSize: "0.5''",
      rating: "800#",
      endconnection: "SW",
      moc: "A105",
      qty: 25,
      Indvalvedim: "406x495x590",
      indvalveweights: "98",
    },
    {
      id: 16,
      category: "Gate",
      valveSize: "3/4''",
      rating: "800#",
      endconnection: "SW",
      moc: "A105",
      qty: 25,
      Indvalvedim: "406x495x590",
      indvalveweights: "98",
    },
    {
      id: 17,
      category: "Gate",
      valveSize: "1''",
      rating: "800#",
      endconnection: "SW",
      moc: "A105",
      qty: 25,
      Indvalvedim: "406x495x590",
      indvalveweights: "98",
    },
    {
      id: 18,
      category: "Gate",
      valveSize: "1 1/2''",
      rating: "800#",
      endconnection: "SW",
      moc: "A105",
      qty: 10,
      Indvalvedim: "406x495x590",
      indvalveweights: "98",
    },
    {
      id: 19,
      category: "Gate",
      valveSize: "0.5''",
      rating: "1500#",
      endconnection: "SW",
      moc: "A105",
      qty: 25,
      Indvalvedim: "406x495x590",
      indvalveweights: "98",
    },
    {
      id: 20,
      category: "Gate",
      valveSize: "3/4''",
      rating: "1500#",
      endconnection: "SW",
      moc: "A105",
      qty: 25,
      Indvalvedim: "406x495x590",
      indvalveweights: "98",
    },
    
    {
      id: 21,
      category: "Gate",
      valveSize: "1''",
      rating: "1500#",
      endconnection: "SW",
      moc: "A105",
      qty: 25,
      Indvalvedim: "406x495x590",
      indvalveweights: "98",
    },
    
    {
      id: 22,
      category: "Gate",
      valveSize: "2''",
      rating: "1500#",
      endconnection: "SW",
      moc: "A105",
      qty: 10,
      Indvalvedim: "406x495x590",
      indvalveweights: "98",
    },
    
    {
      id: 23,
      category: "Gate",
      valveSize: "0.5''",
      rating: "1500#",
      endconnection: "SW",
      moc: "A182 F22",
      qty: 25,
      Indvalvedim: "406x495x590",
      indvalveweights: "98",
    },
    
    {
      id: 24,
      category: "Gate",
      valveSize: "1''",
      rating: "1500#",
      endconnection: "SW",
      moc: "A105",
      qty: 25,
      Indvalvedim: "406x495x590",
      indvalveweights: "98",
    },
    {
        id: 25,
        category: " ",
        valveSize: " ",
        rating: " ",
        endconnection: " ",
        moc: " ",
        qty: " ",
        Indvalvedim: " ",
        indvalveweights: " ",
      },
    {
      id: 26,
      category: "Globe",
      valveSize: "0.5''",
      rating: "800#",
      endconnection: "SW",
      moc: "A105",
      qty: 25,
      Indvalvedim: "406x495x590",
      indvalveweights: "98",
    },
    {
      id: 27,
      category: "Globe",
      valveSize: "3/4''",
      rating: "800#",
      endconnection: "SW",
      moc: "A105",
      qty: 25,
      Indvalvedim: "406x495x590",
      indvalveweights: "98",
    },
    {
      id: 28,
      category: "Globe",
      valveSize: "1''",
      rating: "800#",
      endconnection: "SW",
      moc: "A105",
      qty: 25,
      Indvalvedim: "406x495x590",
      indvalveweights: "98",
    },
    {
      id: 29,
      category: "Globe",
      valveSize: "1 1/2''",
      rating: "800#",
      endconnection: "SW",
      moc: "A105",
      qty: 25,
      Indvalvedim: "406x495x590",
      indvalveweights: "98",
    },
    {
      id: 30,
      category: "Globe",
      valveSize: "0.5''",
      rating: "1500#",
      endconnection: "SW",
      moc: "A105",
      qty: 25,
      Indvalvedim: "406x495x590",
      indvalveweights: "98",
    },
    {
      id: 31,
      category: "Globe",
      valveSize: "3/4''",
      rating: "1500#",
      endconnection: "SW",
      moc: "A105",
      qty: 25,
      Indvalvedim: "406x495x590",
      indvalveweights: "98",
    },
    
    {
      id: 32,
      category: "Globe",
      valveSize: "1''",
      rating: "1500#",
      endconnection: "SW",
      moc: "A105",
      qty: 25,
      Indvalvedim: "406x495x590",
      indvalveweights: "98",
    },
    
    {
      id: 33,
      category: "Globe",
      valveSize: "2''",
      rating: "1500#",
      endconnection: "SW",
      moc: "A105",
      qty: 25,
      Indvalvedim: "406x495x590",
      indvalveweights: "98",
    },
    
    {
      id: 34,
      category: "Globe",
      valveSize: "0.5''",
      rating: "1500#",
      endconnection: "SW",
      moc: "A182 F22",
      qty: 25,
      Indvalvedim: "406x495x590",
      indvalveweights: "98",
    },
    
    {
      id: 35,
      category: "Globe",
      valveSize: "1''",
      rating: "1500#",
      endconnection: "SW",
      moc: "A105",
      qty: 25,
      Indvalvedim: "406x495x590",
      indvalveweights: "98",
    },
    {
        id: 36,
        category: " ",
        valveSize: " ",
        rating: " ",
        endconnection: " ",
        moc: " ",
        qty: " ",
        Indvalvedim: " ",
        indvalveweights: " ",
      },
    {
      id: 37,
      category: "Check",
      valveSize: "0.5''",
      rating: "800#",
      endconnection: "SW",
      moc: "A105",
      qty: 5,
      Indvalvedim: "406x495x590",
      indvalveweights: "98",
    },
    {
      id: 38,
      category: "Check",
      valveSize: "3/4''",
      rating: "800#",
      endconnection: "SW",
      moc: "A105",
      qty: 5,
      Indvalvedim: "406x495x590",
      indvalveweights: "98",
    },
    {
        id: 39,
        category: "Check",
        valveSize: "1''",
        rating: "800#",
        endconnection: "SW",
        moc: "A105",
        qty: 5,
        Indvalvedim: "406x495x590",
        indvalveweights: "98",
      }

  ];